const loremText = [
  'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).',
  'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.',
  'Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
  'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.',
  'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable.If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\'t anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vel mi malesuada, posuere orci ut, tincidunt orci. Curabitur interdum lectus leo, eu ornare odio consequat consequat. Sed dictum nibh quis erat blandit, id iaculis urna imperdiet. Phasellus bibendum, mauris vitae sagittis tempus, eros orci pharetra neque, ut molestie libero justo et arcu. Vestibulum sed finibus urna. Praesent dapibus urna in sapien faucibus, id pretium risus convallis. Sed sodales purus non nibh sodales, non laoreet elit condimentum. Curabitur tristique, est quis venenatis dictum, neque dolor scelerisque nisi, sed accumsan nisl lorem vel dui. Donec feugiat suscipit laoreet. Nam volutpat nunc sed bibendum condimentum. Nullam eu metus nisl.',
  'Pellentesque quis fermentum mi, eu dapibus tortor. Nam pulvinar sapien et pretium blandit. Sed vel commodo libero. Cras dignissim nisl ut eros aliquet, sit amet posuere mi blandit. Ut blandit pellentesque quam eget cursus. Morbi at diam est. Pellentesque vulputate rutrum neque, non congue odio ornare et. Sed fermentum ligula vitae leo semper, in scelerisque ante luctus. Maecenas facilisis neque sed mi placerat, vel interdum lectus dignissim. Curabitur aliquam, nulla vitae dictum bibendum, metus leo mollis enim, vitae commodo purus nisl id justo. Donec aliquet sem sed ligula egestas, et mollis mi finibus. Pellentesque fermentum risus a ante placerat, non cursus metus blandit. Nullam egestas ut justo quis varius. Nullam fringilla et ante eget placerat. Morbi ac elementum mauris, a luctus odio.',
  'Suspendisse quis lectus venenatis, cursus massa et, aliquam orci. Donec fermentum vulputate purus quis mattis. Ut rhoncus ante ac arcu sagittis, a varius eros suscipit. Phasellus pulvinar justo non dapibus bibendum. Etiam aliquet purus at tellus aliquet luctus. In hac habitasse platea dictumst. Quisque vitae tellus velit. Integer hendrerit laoreet massa eget rhoncus. Praesent hendrerit dolor vel sem lacinia consectetur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed imperdiet consectetur purus, vitae blandit tellus luctus auctor. Suspendisse quis blandit nulla. Sed porttitor eget dui eget sagittis. Sed tempor sollicitudin varius. Proin lacus lorem, mollis ac aliquet vitae, rhoncus vel ligula.',
  'Maecenas non velit sit amet ex blandit viverra in ut ante. Curabitur vulputate imperdiet diam sit amet interdum. Pellentesque quam dolor, ultrices ut eros non, pretium bibendum nibh. Maecenas congue, ligula nec egestas dictum, neque lacus consectetur sapien, id fringilla lorem enim ac ligula. Pellentesque condimentum aliquam lectus non sollicitudin. Aliquam porttitor nulla odio, ac imperdiet ligula semper at. Donec mattis tristique elit consequat eleifend. Quisque nec porttitor purus, ac efficitur mauris.',
  'Integer vitae metus eleifend purus mattis molestie. Pellentesque eros risus, viverra eget mi sed, sollicitudin euismod libero. Nunc eget odio porttitor, egestas ligula quis, tristique quam. Nullam vestibulum sem quis diam fringilla, quis volutpat purus sodales. Nullam nibh ligula, fermentum sed pulvinar in, consectetur et odio. Vivamus pretium, turpis vitae aliquet aliquet, turpis mi vehicula lorem, rhoncus pulvinar mauris turpis nec arcu. Aliquam ullamcorper ut eros quis mollis. In ac tellus aliquam, egestas arcu ac, hendrerit est.'
]

export default loremText;
